use super::canvas::CanvasComponent;

pub fn generate_leptos_code(components: &[CanvasComponent]) -> String {
    let mut code = String::from("// Generated by Leptos Studio\nuse leptos::*;\n\n#[component]\npub fn GeneratedView() -> impl IntoView {\n    view! {\n");
    fn write_components(components: &[CanvasComponent], code: &mut String, indent: &str) {
        for comp in components {
            match comp {
                CanvasComponent::Button { label } => {
                    code.push_str(&format!("{}<button>{{\"{}\"}}</button>\n", indent, label));
                }
                CanvasComponent::Text { content } => {
                    code.push_str(&format!("{}<span>{{\"{}\"}}</span>\n", indent, content));
                }
                CanvasComponent::Input { placeholder } => {
                    code.push_str(&format!("{}<input placeholder=\"{}\" />\n", indent, placeholder));
                }
                CanvasComponent::Custom { name, template } => {
                    code.push_str(&format!("{}// Custom: {}\n{}/* {} */\n", indent, name, indent, template));
                }
                CanvasComponent::Container { children } => {
                    code.push_str(&format!("{}<div class=\"container\">\n", indent));
                    write_components(children, code, &format!("{}    ", indent));
                    code.push_str(&format!("{}</div>\n", indent));
                }
            }
        }
    }
    write_components(components, &mut code, "        ");
    code.push_str("    }\n}\n");
    code
}
