use super::canvas::CanvasComponent;

pub fn generate_leptos_code(components: &[CanvasComponent]) -> String {
    let mut code = String::from("// Generated by Leptos Studio\nuse leptos::*;\n\n#[component]\npub fn GeneratedView() -> impl IntoView {\n    view! {\n");
    for comp in components {
        match comp {
            CanvasComponent::Button { label } => {
                code.push_str(&format!("        <button>{{\"{}\"}}</button>\n", label));
            }
            CanvasComponent::Text { content } => {
                code.push_str(&format!("        <span>{{\"{}\"}}</span>\n", content));
            }
            CanvasComponent::Input { placeholder } => {
                code.push_str(&format!("        <input placeholder=\"{}\" />\n", placeholder));
            }
            CanvasComponent::Custom { name, template } => {
                code.push_str(&format!("        // Custom: {}\n        /* {} */\n", name, template));
            }
            CanvasComponent::Container { .. } => {
                code.push_str("        <div class=\"container\">Container</div>\n");
            }
        }
    }
    code.push_str("    }\n}\n");
    code
}
