pub fn generate_html_code(components: &[CanvasComponent], custom_components: &[LibraryComponent]) -> String {
    fn write_html(components: &[CanvasComponent], custom_components: &[LibraryComponent], code: &mut String, indent: &str) {
        for comp in components {
            match comp {
                CanvasComponent::Button { label } => {
                    code.push_str(&format!("{}<button>{}</button>\n", indent, label));
                }
                CanvasComponent::Text { content } => {
                    code.push_str(&format!("{}<span>{}</span>\n", indent, content));
                }
                CanvasComponent::Input { placeholder } => {
                    code.push_str(&format!("{}<input placeholder=\"{}\" />\n", indent, placeholder));
                }
                CanvasComponent::Custom { name } => {
                    let template = custom_components.iter().find(|c| c.name == *name).and_then(|c| c.template.clone()).unwrap_or_else(|| "<i>Template not found</i>".to_string());
                    code.push_str(&format!("{}<!-- Custom: {} -->\n{}{}\n", indent, name, indent, template));
                }
                CanvasComponent::Container { children } => {
                    code.push_str(&format!("{}<div class=\"container\">\n", indent));
                    write_html(children, custom_components, code, &format!("{}    ", indent));
                    code.push_str(&format!("{}</div>\n", indent));
                }
            }
        }
    }
    let mut code = String::from("<!-- Generated by Leptos Studio -->\n");
    write_html(components, custom_components, &mut code, "");
    code
}

pub fn generate_markdown_code(components: &[CanvasComponent], custom_components: &[LibraryComponent]) -> String {
    fn write_md(components: &[CanvasComponent], custom_components: &[LibraryComponent], code: &mut String, depth: usize) {
        let indent = "  ".repeat(depth);
        for comp in components {
            match comp {
                CanvasComponent::Button { label } => {
                    code.push_str(&format!("{}- **Button:** `{}`\n", indent, label));
                }
                CanvasComponent::Text { content } => {
                    code.push_str(&format!("{}- **Text:** `{}`\n", indent, content));
                }
                CanvasComponent::Input { placeholder } => {
                    code.push_str(&format!("{}- **Input:** placeholder=`{}`\n", indent, placeholder));
                }
                CanvasComponent::Custom { name } => {
                    let template = custom_components.iter().find(|c| c.name == *name).and_then(|c| c.template.clone()).unwrap_or_else(|| "<i>Template not found</i>".to_string());
                    code.push_str(&format!("{}- **Custom:** `{}`\n{}  Template: \n{}    {}\n", indent, name, indent, indent, template.replace("\n", &format!("\n{}    ", indent))));
                }
                CanvasComponent::Container { children } => {
                    code.push_str(&format!("{}- **Container:**\n", indent));
                    write_md(children, custom_components, code, depth + 1);
                }
            }
        }
    }
    let mut code = String::from("# UI Layout\n\n");
    write_md(components, custom_components, &mut code, 0);
    code
}
use super::canvas::CanvasComponent;

use crate::builder::component_library::LibraryComponent;

pub fn generate_leptos_code(components: &[CanvasComponent], custom_components: &[LibraryComponent]) -> String {
    let mut code = String::from("// Generated by Leptos Studio\nuse leptos::*;\n\n#[component]\npub fn GeneratedView() -> impl IntoView {\n    view! {\n");
    fn write_components(components: &[CanvasComponent], custom_components: &[LibraryComponent], code: &mut String, indent: &str) {
        for comp in components {
            match comp {
                CanvasComponent::Button { label } => {
                    code.push_str(&format!("{}<button>{{\"{}\"}}</button>\n", indent, label));
                }
                CanvasComponent::Text { content } => {
                    code.push_str(&format!("{}<span>{{\"{}\"}}</span>\n", indent, content));
                }
                CanvasComponent::Input { placeholder } => {
                    code.push_str(&format!("{}<input placeholder=\"{}\" />\n", indent, placeholder));
                }
                CanvasComponent::Custom { name } => {
                    let template = custom_components.iter().find(|c| c.name == *name).and_then(|c| c.template.clone()).unwrap_or_else(|| "<i>Template not found</i>".to_string());
                    code.push_str(&format!("{}// Custom: {}\n{}/* {} */\n", indent, name, indent, template));
                }
                CanvasComponent::Container { children } => {
                    code.push_str(&format!("{}<div class=\"container\">\n", indent));
                    write_components(children, custom_components, code, &format!("{}    ", indent));
                    code.push_str(&format!("{}</div>\n", indent));
                }
            }
        }
    }
    write_components(components, custom_components, &mut code, "        ");
    code.push_str("    }\n}\n");
    code
}
