# Configuration for GitHub labeler action

# Documentation
documentation:
  - changed-files:
    - any-glob-to-any-file: ['**/*.md', 'docs/**/*']

# CI/CD
ci:
  - changed-files:
    - any-glob-to-any-file: ['.github/**/*', '.gitlab-ci.yml']

# Source code
rust:
  - changed-files:
    - any-glob-to-any-file: ['**/*.rs', 'Cargo.toml', 'Cargo.lock']

# Tests
tests:
  - changed-files:
    - any-glob-to-any-file: ['tests/**/*', '**/*_test.rs', '**/test_*.rs']

# Building/Dependencies
dependencies:
  - changed-files:
    - any-glob-to-any-file: ['Cargo.toml', 'Cargo.lock']

# Styling
ui:
  - changed-files:
    - any-glob-to-any-file: ['**/*.css', 'style.css']

# HTML/Web
web:
  - changed-files:
    - any-glob-to-any-file: ['**/*.html', 'index.html', 'Trunk.toml']

# Domain logic
domain:
  - changed-files:
    - any-glob-to-any-file: ['src/domain/**/*']

# Services
services:
  - changed-files:
    - any-glob-to-any-file: ['src/services/**/*']

# UI Builder
builder:
  - changed-files:
    - any-glob-to-any-file: ['src/builder/**/*']

# State management
state:
  - changed-files:
    - any-glob-to-any-file: ['src/state/**/*']
