// Integration test: Simulate layout changes and export
use leptos_studio::builder::canvas::CanvasComponent;
use leptos_studio::builder::export::generate_leptos_code;

#[test]
fn test_export_code_generation() {
    let layout = vec![
        CanvasComponent::Button { label: "Hello".to_string() },
        CanvasComponent::Text { content: "World".to_string() },
        CanvasComponent::Container { children: vec![
            CanvasComponent::Input { placeholder: "Type here".to_string() }
        ]},
    ];
    let code = generate_leptos_code(&layout);
    let expected = r#"// Generated by Leptos Studio
use leptos::*;

#[component]
pub fn GeneratedView() -> impl IntoView {
    view! {
        <button>{"Hello"}</button>
        <span>{"World"}</span>
        <div class="container">
            <input placeholder="Type here" />
        </div>
    }
}
"#;
    let normalize = |s: &str| s.chars().filter(|c| !c.is_whitespace()).collect::<String>();
    assert_eq!(normalize(&code), normalize(expected), "Output tidak sesuai snapshot.\nOutput:\n{}\nExpected:\n{}", code, expected);
}
