use crate::services::{Template, TemplateCategory, TemplateService};
use crate::state::app_state::{AppState, Notification};
use leptos::prelude::*;

#[component]
pub fn SaveTemplateModal(show: RwSignal<bool>, on_close: Callback<()>) -> impl IntoView {
    let app_state = AppState::expect_context();

    let name = RwSignal::new(String::new());
    let description = RwSignal::new(String::new());
    let tags = RwSignal::new(String::new());
    let loading = RwSignal::new(false);

    let on_save = move |_| {
        let name_val = name.get();
        if name_val.trim().is_empty() {
            app_state
                .ui
                .notify(Notification::error("Template name is required".to_string()));
            return;
        }

        loading.set(true);

        // Capture current canvas state
        let components = app_state.canvas.components.get();

        // Create tags list
        let tag_list: Vec<String> = tags
            .get()
            .split(',')
            .map(|s| s.trim().to_string())
            .filter(|s| !s.is_empty())
            .collect();

        let template = Template::new(
            "", // ID will be generated by backend
            &name_val,
            &description.get(),
            TemplateCategory::Custom,
            components,
        )
        .with_tags(tag_list.iter().map(|s| s.as_str()).collect());

        leptos::task::spawn_local(async move {
            match TemplateService::save_custom_template(&template).await {
                Ok(_) => {
                    app_state.ui.notify(Notification::success(
                        "Template saved successfully".to_string(),
                    ));
                    name.set(String::new());
                    description.set(String::new());
                    tags.set(String::new());
                    on_close.run(());
                }
                Err(e) => {
                    app_state.ui.notify(Notification::error(format!(
                        "Failed to save template: {}",
                        e.user_message()
                    )));
                }
            }
            loading.set(false);
        });
    };

    view! {
        <Show when=move || show.get()>
            <div class="modal-overlay">
                <div class="modal-content" style="max-width: 500px">
                    <h3>"Save as Template"</h3>

                    <div class="form-group" style="margin-bottom: 1rem">
                        <label style="display: block; margin-bottom: 0.5rem; font-weight: 500">"Name"</label>
                        <input
                            type="text"
                            class="input"
                            prop:value=name
                            on:input=move |ev| name.set(event_target_value(&ev))
                            placeholder="My Awesome Template"
                            style="width: 100%; padding: 0.5rem; border: 1px solid #ccc; border-radius: 4px;"
                            autofocus
                        />
                    </div>

                    <div class="form-group" style="margin-bottom: 1rem">
                        <label style="display: block; margin-bottom: 0.5rem; font-weight: 500">"Description"</label>
                        <textarea
                            class="input"
                            prop:value=description
                            on:input=move |ev| description.set(event_target_value(&ev))
                            placeholder="Describe your template..."
                            rows=3
                            style="width: 100%; padding: 0.5rem; border: 1px solid #ccc; border-radius: 4px;"
                        />
                    </div>

                    <div class="form-group" style="margin-bottom: 1.5rem">
                        <label style="display: block; margin-bottom: 0.5rem; font-weight: 500">"Tags (comma separated)"</label>
                        <input
                            type="text"
                            class="input"
                            prop:value=tags
                            on:input=move |ev| tags.set(event_target_value(&ev))
                            placeholder="landing, dark, mobile"
                            style="width: 100%; padding: 0.5rem; border: 1px solid #ccc; border-radius: 4px;"
                        />
                    </div>

                    <div class="modal-actions" style="display: flex; justify-content: flex-end; gap: 0.5rem">
                        <button
                            class="btn btn-primary"
                            disabled=move || loading.get()
                            on:click=on_save
                        >
                            {move || if loading.get() { "Saving..." } else { "Save Template" }}
                        </button>
                        <button
                            class="btn btn-ghost"
                            on:click=move |_| on_close.run(())
                        >
                            "Cancel"
                        </button>
                    </div>
                </div>
            </div>
        </Show>
    }
}
